#!/usr/bin/env python2
# vim:ft=python

def main(*args):
    if len(args) == 1:
        replace = False
        filename = args[0]
    elif len(args) == 2 and args[0] == "-w":
        replace = True
        filename = args[1]
    else:
        print "Usage: %s -w <file>"%(sys.argv[0])
        sys.exit(1)

    i = 0
    s = ""
    for line in open(filename).readlines():
        if replace:
            s += "%d   %s"%( i, line )
        else:
            print i, line,
        i += 1
    if replace:
        open(filename,'w').write(s)

if __name__ == "__main__":
    import sys
    main(*sys.argv[1:])
